"""empty message

Revision ID: efab4bf794db
Revises: 
Create Date: 2021-04-21 22:18:36.601916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efab4bf794db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('bathrooms', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('description', sa.String(length=80), nullable=True))
    op.add_column('properties', sa.Column('property_type', sa.String(length=80), nullable=True))
    op.drop_column('properties', 'room')
    op.drop_column('properties', 'descript')
    op.drop_column('properties', 'bathroom')
    op.drop_column('properties', 'propertyT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyT', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('bathroom', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('descript', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('room', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('properties', 'property_type')
    op.drop_column('properties', 'description')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('properties', 'bathrooms')
    # ### end Alembic commands ###
